version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis on default port
    command: redis-server --appendonly yes # Enable data persistence
    volumes:
      - redis-data:/data # Persistent storage for Redis
    restart: unless-stopped # Always restart the container unless stopped manually

volumes:
  redis-data:
